feat: use Mythic Beasts DNS API v2

diff --git a/common/mythic-dns01 b/common/mythic-dns01
--- a/common/mythic-dns01
+++ b/common/mythic-dns01
@@ -6,39 +6,58 @@ CONFIG=${MYTHIC_DNS_CONFIG:-/etc/dehydrated/dnsapi.config.txt}
 SLEEP=5
 MAXTRIES=60
 
-# all our public authoritative servers
-SERVERS="ns1.mythic-beasts.com ns2.mythic-beasts.com"
-
-# dig options
-DIGOPT='+time=1 +tries=1 +short'
-
 wait_for_dns() {
-    local key val i s
+    local key val i s dns_domain dns_api_id dns_api_secret host zone
     key="$1" val="$2"
-    for i in $(seq $MAXTRIES); do
-        for s in $SERVERS; do
-            if ! dig $DIGOPT @$s $key txt | grep -q -e $val; then
-               sleep $SLEEP
-               continue 2
+    while read dns_domain dns_api_id dns_api_secret; do
+        case $key in
+        *$dns_domain)
+            zone=$(awk -F. '{print $(NF-1) "." $NF}' <<< $dns_domain)
+            host=$(basename $key .$zone)
+            for i in $(seq $MAXTRIES); do
+                RES=$(curl -fqs --user "$dns_api_id":"$dns_api_secret" -o /dev/null -w '%{http_code}' https://api.mythic-beasts.com/dns/v2/zones/$zone/records/$host/TXT?verify)
+                case $RES in
+                    200)
+                        echo " ++ DNS record updated"
+                        ;;
+                    409)
+                        echo " ++ Still waiting ($i/$MAXTRIES)"
+                        sleep $SLEEP
+                        continue
+                        ;;
+                    *)
+                        echo " ++ Unexpected response code: $RES" >$2
+                        exit 1
+                        ;;
+                esac
+                break
+            done
+            if [ "$i" -eq "$MAXTRIES" ]; then
+                echo " ++ Challenge record not found in DNS" >&2
+                exit 1
             fi
-        done
-        break
-    done
-    if [ "$i" -eq "$MAXTRIES" ]; then
-        echo challenge record not found in DNS >&2
-        exit 1
-    fi
+            break
+            ;;
+        esac
+    done < $CONFIG
 }
 
 call_api() {
-    local action key val dns_domain dns_api_pass rr_part
+    local action key val dns_domain dns_api_id dns_api_secret host zone
     action="$1" key="$2" val="$3"
-    while read dns_domain dns_api_pass; do
+    while read dns_domain dns_api_id dns_api_secret; do
         case $key in
         *$dns_domain)
-            rr_part=$(basename $key .$dns_domain)
-            echo -n "$dns_api_pass" |
-                curl --data-urlencode "domain=$dns_domain" --data-urlencode "password@-" --data-urlencode "command=$action $rr_part 30 TXT $val" https://dnsapi.mythic-beasts.com/
+            zone=$(awk -F. '{print $(NF-1) "." $NF}' <<< $dns_domain)
+            host=$(basename $key .$zone)
+            case $action in
+            ADD)
+                curl -fqsS --user "$dns_api_id":"$dns_api_secret" -o /dev/null -X PUT https://api.mythic-beasts.com/dns/v2/zones/$zone/records/$host/TXT -d "data=$val" -d "ttl=1"
+                ;;
+            DELETE)
+                curl -fqsS --user "$dns_api_id":"$dns_api_secret" -o /dev/null -X DELETE https://api.mythic-beasts.com/dns/v2/zones/$zone/records/$host/TXT
+                ;;
+            esac
             break
             ;;
         esac
